[package]
name = "system-system"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true


[dependencies]
syn = {version = "1.0.58", features = ["full"]}
quote = "0.6.10"

rust-embed = "5.8.0"
